import { Stack } from '@mui/material'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Stack
          direction='column'
          justifyContent='space-between'
          minHeight='100vh'
          bgcolor='#F5F5F5'
        >
          <Navbar />
          {children}
          <Footer />
        </Stack>
      </body>
    </html>
  )
}
